### ISSUE TITLE
Allow building with `transformers-0.6.*`

### ISSUE THREAD

**Issue by RyanGlScott** [haskellari/microstache#30]
As far as I can tell, the upper version bounds can be lifted without any other changes:

```diff
diff --git a/microstache.cabal b/microstache.cabal
index daa4ec2..e225db6 100644
--- a/microstache.cabal
+++ b/microstache.cabal
@@ -57,7 +57,7 @@ library
     , filepath              >=1.3.0.0 && <1.5
     , parsec                >=3.1.11  && <3.2
     , text                  >=1.2     && <1.3
-    , transformers          >=0.3.0.0 && <0.6
+    , transformers          >=0.3.0.0 && <0.7
     , unordered-containers  >=0.2.5   && <0.3
     , vector                >=0.11    && <0.13
```

**Comment by phadej** [comment]
`parsec` depends on `mtl`, so I cannot test this for sure.

**Comment by RyanGlScott** [comment]
Ah, quite right. FWIW, I was able to compile `parsec` with `--allow-newer=parsec:mtl` and no other changes, so I didn't even really notice that part until now.

**Comment by RyanGlScott** [comment]
[`parsec-3.1.15.1`](https://hackage.haskell.org/package/parsec-3.1.15.1) is compatible with `mtl-2.3.*`, so I believe this is now unblocked.
